export type FlyerTemplate = {
  id: string;
  name: string;
  description: string;
  /** page background (css value) */
  bg: string;
  /** header band */
  header: string;
  headerText: string;
  /** product card */
  card: string;
  cardText: string;
  cardBorder: string;
  /** price pill */
  price: string;
  priceText: string;
  accent: string;
  accentText: string;
  radius: string;
  headingFont: string;
  uppercaseNames: boolean;
};

export const TEMPLATES: FlyerTemplate[] = [
  {
    id: "tradicional",
    name: "Supermercado tradicional",
    description: "Vermelho e amarelo clássico de encarte de mercado.",
    bg: "#e11d2f",
    header: "#ffd400",
    headerText: "#8a0f16",
    card: "#ffffff",
    cardText: "#1c1917",
    cardBorder: "#f5c6c9",
    price: "#ffd400",
    priceText: "#8a0f16",
    accent: "#8a0f16",
    accentText: "#ffffff",
    radius: "14px",
    headingFont: "'Archivo Black', system-ui, sans-serif",
    uppercaseNames: true,
  },
  {
    id: "agressiva",
    name: "Oferta agressiva",
    description: "Preços gigantes, explosões amarelas, alto impacto.",
    bg: "#111111",
    header: "#ffe000",
    headerText: "#111111",
    card: "#1b1b1b",
    cardText: "#ffffff",
    cardBorder: "#3a3a3a",
    price: "#ffe000",
    priceText: "#111111",
    accent: "#ff2d2d",
    accentText: "#ffffff",
    radius: "6px",
    headingFont: "'Archivo Black', system-ui, sans-serif",
    uppercaseNames: true,
  },
  {
    id: "minimalista",
    name: "Minimalista",
    description: "Fundo claro, tipografia limpa, muito respiro.",
    bg: "#f4f4f0",
    header: "#111111",
    headerText: "#ffffff",
    card: "#ffffff",
    cardText: "#111111",
    cardBorder: "#e3e3dd",
    price: "#111111",
    priceText: "#ffffff",
    accent: "#111111",
    accentText: "#ffffff",
    radius: "4px",
    headingFont: "'Barlow Condensed', system-ui, sans-serif",
    uppercaseNames: false,
  },
  {
    id: "premium",
    name: "Premium",
    description: "Preto e dourado para lojas mais sofisticadas.",
    bg: "#0f1114",
    header: "#c9a227",
    headerText: "#0f1114",
    card: "#171a1f",
    cardText: "#f5f0e6",
    cardBorder: "#33291a",
    price: "#c9a227",
    priceText: "#0f1114",
    accent: "#c9a227",
    accentText: "#0f1114",
    radius: "10px",
    headingFont: "'Barlow Condensed', system-ui, sans-serif",
    uppercaseNames: false,
  },
  {
    id: "feirao",
    name: "Feirão",
    description: "Verde e laranja, cara de feira livre.",
    bg: "#0f7a3d",
    header: "#ff8a00",
    headerText: "#ffffff",
    card: "#ffffff",
    cardText: "#123",
    cardBorder: "#cbe6d4",
    price: "#ff8a00",
    priceText: "#ffffff",
    accent: "#0a5a2c",
    accentText: "#ffffff",
    radius: "18px",
    headingFont: "'Archivo Black', system-ui, sans-serif",
    uppercaseNames: true,
  },
  {
    id: "relampago",
    name: "Oferta relâmpago",
    description: "Azul elétrico com destaque de urgência.",
    bg: "#0b2ea8",
    header: "#00e0ff",
    headerText: "#062066",
    card: "#ffffff",
    cardText: "#0b1730",
    cardBorder: "#c3d4ff",
    price: "#ffe000",
    priceText: "#062066",
    accent: "#00e0ff",
    accentText: "#062066",
    radius: "12px",
    headingFont: "'Archivo Black', system-ui, sans-serif",
    uppercaseNames: true,
  },
  {
    id: "fimdesemana",
    name: "Fim de semana",
    description: "Roxo e rosa, ofertas de sexta a domingo.",
    bg: "#3b0f6b",
    header: "#ff2e8b",
    headerText: "#ffffff",
    card: "#ffffff",
    cardText: "#2a0b4d",
    cardBorder: "#e6cdf5",
    price: "#ff2e8b",
    priceText: "#ffffff",
    accent: "#ffd400",
    accentText: "#3b0f6b",
    radius: "16px",
    headingFont: "'Barlow Condensed', system-ui, sans-serif",
    uppercaseNames: true,
  },
  {
    id: "festival",
    name: "Festival de preços",
    description: "Faixas coloridas e clima de festa.",
    bg: "#ff5a1f",
    header: "#1d1d1b",
    headerText: "#ffd400",
    card: "#ffffff",
    cardText: "#1d1d1b",
    cardBorder: "#ffd9c7",
    price: "#1d1d1b",
    priceText: "#ffd400",
    accent: "#ffd400",
    accentText: "#1d1d1b",
    radius: "20px",
    headingFont: "'Archivo Black', system-ui, sans-serif",
    uppercaseNames: true,
  },
  {
    id: "hortifruti",
    name: "Hortifruti",
    description: "Verde claro e fresco para frutas e verduras.",
    bg: "#d8f3c4",
    header: "#2f7a12",
    headerText: "#ffffff",
    card: "#ffffff",
    cardText: "#1c3b0d",
    cardBorder: "#bfe3a5",
    price: "#2f7a12",
    priceText: "#ffffff",
    accent: "#f7b500",
    accentText: "#1c3b0d",
    radius: "22px",
    headingFont: "'Barlow Condensed', system-ui, sans-serif",
    uppercaseNames: false,
  },
  {
    id: "churrasco",
    name: "Churrasco",
    description: "Marrom e brasa para carnes e bebidas.",
    bg: "#4a1c10",
    header: "#e8560f",
    headerText: "#fff6ea",
    card: "#fff6ea",
    cardText: "#3a1509",
    cardBorder: "#e0c3a8",
    price: "#e8560f",
    priceText: "#fff6ea",
    accent: "#ffb703",
    accentText: "#3a1509",
    radius: "10px",
    headingFont: "'Archivo Black', system-ui, sans-serif",
    uppercaseNames: true,
  },
];

export function templateById(id: string): FlyerTemplate {
  return TEMPLATES.find((t) => t.id === id) ?? TEMPLATES[0]!;
}
