/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlyersRouteImport } from './routes/flyers'
import { Route as FlyerEditorRouteImport } from './routes/flyers/$flyerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const FlyersRoute = FlyersRouteImport.update({
  id: '/flyers',
  path: '/flyers',
  getParentRoute: () => rootRouteImport,
} as any)

const FlyerEditorRoute = FlyerEditorRouteImport.update({
  id: '/flyers/$flyerId',
  path: '/flyers/$flyerId',
  getParentRoute: () => FlyersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute,
  '/flyers': typeof FlyersRoute,
  '/flyers/$flyerId': typeof FlyerEditorRoute,
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute,
  '/flyers': typeof FlyersRoute,
  '/flyers/$flyerId': typeof FlyerEditorRoute,
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport,
  '/': typeof IndexRoute,
  '/flyers': typeof FlyersRoute,
  '/flyers/$flyerId': typeof FlyerEditorRoute,
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/flyers' | '/flyers/$flyerId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flyers' | '/flyers/$flyerId'
  id: '__root__' | '/' | '/flyers' | '/flyers/$flyerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute,
  FlyersRoute: typeof FlyersRoute,
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flyers': {
      id: '/flyers'
      path: '/flyers'
      fullPath: '/flyers'
      preLoaderRoute: typeof FlyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flyers/$flyerId': {
      id: '/flyers/$flyerId'
      path: '/flyers/$flyerId'
      fullPath: '/flyers/$flyerId'
      preLoaderRoute: typeof FlyerEditorRouteImport
      parentRoute: typeof FlyersRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlyersRoute: FlyersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
